#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorTeamStatus

#include "Basic.hpp"

#include "AthenaSpectatorTeamStatus_classes.hpp"
#include "AthenaSpectatorTeamStatus_parameters.hpp"


namespace SDK
{

// Function AthenaSpectatorTeamStatus.AthenaSpectatorTeamStatus_C.UpdatePlayerData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      NewSource                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorTeamStatus_C::UpdatePlayerData(class UAthenaRemotePlayerViewData* NewSource)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorTeamStatus_C", "UpdatePlayerData");

	Params::AthenaSpectatorTeamStatus_C_UpdatePlayerData Parms{};

	Parms.NewSource = NewSource;

	UObject::ProcessEvent(Func, &Parms);
}

}

