#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorMatchStatus

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function AthenaSpectatorMatchStatus.AthenaSpectatorMatchStatus_C.ExecuteUbergraph_AthenaSpectatorMatchStatus
// 0x0058 (0x0058 - 0x0000)
struct AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_MatchTimeText;                        // 0x0008(0x0018)(ConstParm)
	class FText                                   K2Node_Event_SafeZonePhaseTxt;                     // 0x0020(0x0018)(ConstParm)
	class FText                                   K2Node_Event_NewLocation;                          // 0x0038(0x0018)(ConstParm)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus) == 0x000008, "Wrong alignment on AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus");
static_assert(sizeof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus) == 0x000058, "Wrong size on AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, EntryPoint) == 0x000000, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, Temp_byte_Variable) == 0x000004, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, Temp_byte_Variable1) == 0x000005, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, K2Node_Event_MatchTimeText) == 0x000008, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::K2Node_Event_MatchTimeText' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, K2Node_Event_SafeZonePhaseTxt) == 0x000020, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::K2Node_Event_SafeZonePhaseTxt' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, K2Node_Event_NewLocation) == 0x000038, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::K2Node_Event_NewLocation' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, CallFunc_TextIsEmpty_ReturnValue) == 0x000050, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, Temp_bool_Variable) == 0x000051, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus, K2Node_Select_Default) == 0x000052, "Member 'AthenaSpectatorMatchStatus_C_ExecuteUbergraph_AthenaSpectatorMatchStatus::K2Node_Select_Default' has a wrong offset!");

// Function AthenaSpectatorMatchStatus.AthenaSpectatorMatchStatus_C.UpdateMatchTimeText
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorMatchStatus_C_UpdateMatchTimeText final
{
public:
	class FText                                   MatchTimeText;                                     // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaSpectatorMatchStatus_C_UpdateMatchTimeText) == 0x000008, "Wrong alignment on AthenaSpectatorMatchStatus_C_UpdateMatchTimeText");
static_assert(sizeof(AthenaSpectatorMatchStatus_C_UpdateMatchTimeText) == 0x000018, "Wrong size on AthenaSpectatorMatchStatus_C_UpdateMatchTimeText");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_UpdateMatchTimeText, MatchTimeText) == 0x000000, "Member 'AthenaSpectatorMatchStatus_C_UpdateMatchTimeText::MatchTimeText' has a wrong offset!");

// Function AthenaSpectatorMatchStatus.AthenaSpectatorMatchStatus_C.UpdatePlayerLocationText
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText final
{
public:
	class FText                                   NewLocation;                                       // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText) == 0x000008, "Wrong alignment on AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText");
static_assert(sizeof(AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText) == 0x000018, "Wrong size on AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText, NewLocation) == 0x000000, "Member 'AthenaSpectatorMatchStatus_C_UpdatePlayerLocationText::NewLocation' has a wrong offset!");

// Function AthenaSpectatorMatchStatus.AthenaSpectatorMatchStatus_C.UpdateStormPhaseText
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorMatchStatus_C_UpdateStormPhaseText final
{
public:
	class FText                                   SafeZonePhaseTxt;                                  // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaSpectatorMatchStatus_C_UpdateStormPhaseText) == 0x000008, "Wrong alignment on AthenaSpectatorMatchStatus_C_UpdateStormPhaseText");
static_assert(sizeof(AthenaSpectatorMatchStatus_C_UpdateStormPhaseText) == 0x000018, "Wrong size on AthenaSpectatorMatchStatus_C_UpdateStormPhaseText");
static_assert(offsetof(AthenaSpectatorMatchStatus_C_UpdateStormPhaseText, SafeZonePhaseTxt) == 0x000000, "Member 'AthenaSpectatorMatchStatus_C_UpdateStormPhaseText::SafeZonePhaseTxt' has a wrong offset!");

}

