#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorPlayerStatus

#include "Basic.hpp"

#include "AthenaSpectatorPlayerStatus_classes.hpp"
#include "AthenaSpectatorPlayerStatus_parameters.hpp"


namespace SDK
{

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.ExecuteUbergraph_AthenaSpectatorPlayerStatus
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::ExecuteUbergraph_AthenaSpectatorPlayerStatus(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "ExecuteUbergraph_AthenaSpectatorPlayerStatus");

	Params::AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.SquadDatasChanged
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      SquadMember1                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAthenaRemotePlayerViewData*      SquadMember2                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAthenaRemotePlayerViewData*      SquadMember3                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::SquadDatasChanged(const class UAthenaRemotePlayerViewData* SquadMember1, const class UAthenaRemotePlayerViewData* SquadMember2, const class UAthenaRemotePlayerViewData* SquadMember3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "SquadDatasChanged");

	Params::AthenaSpectatorPlayerStatus_C_SquadDatasChanged Parms{};

	Parms.SquadMember1 = SquadMember1;
	Parms.SquadMember2 = SquadMember2;
	Parms.SquadMember3 = SquadMember3;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.FollowedPlayerChanged
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerStateAthena*           NewFollowedPlayer                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::FollowedPlayerChanged(const class AFortPlayerStateAthena* NewFollowedPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "FollowedPlayerChanged");

	Params::AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged Parms{};

	Parms.NewFollowedPlayer = NewFollowedPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerTeam
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamNumber                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     TeamColor                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::UpdatePlayerTeam(const int32 TeamNumber, const struct FLinearColor& TeamColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "UpdatePlayerTeam");

	Params::AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam Parms{};

	Parms.TeamNumber = TeamNumber;
	Parms.TeamColor = std::move(TeamColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerNameText
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             PlayerNameText_0                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaSpectatorPlayerStatus_C::UpdatePlayerNameText(const class FText& PlayerNameText_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "UpdatePlayerNameText");

	Params::AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText Parms{};

	Parms.PlayerNameText_0 = std::move(PlayerNameText_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaSpectatorPlayerStatus_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Update Squad Datas
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      Squad_1                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAthenaRemotePlayerViewData*      Squad_2                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAthenaRemotePlayerViewData*      Squad_3                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::Update_Squad_Datas(class UAthenaRemotePlayerViewData* Squad_1, class UAthenaRemotePlayerViewData* Squad_2, class UAthenaRemotePlayerViewData* Squad_3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "Update Squad Datas");

	Params::AthenaSpectatorPlayerStatus_C_Update_Squad_Datas Parms{};

	Parms.Squad_1 = Squad_1;
	Parms.Squad_2 = Squad_2;
	Parms.Squad_3 = Squad_3;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Update Squad Member Data
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      PlayerData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAthenaSpectatorTeamStatus_C*     TeamStatusWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::Update_Squad_Member_Data(class UAthenaRemotePlayerViewData* PlayerData, class UAthenaSpectatorTeamStatus_C* TeamStatusWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "Update Squad Member Data");

	Params::AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data Parms{};

	Parms.PlayerData = PlayerData;
	Parms.TeamStatusWidget = TeamStatusWidget;

	UObject::ProcessEvent(Func, &Parms);
}

}

