#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorPlayerStatus

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C
// 0x0048 (0x0288 - 0x0240)
class UAthenaSpectatorPlayerStatus_C final : public UAthenaPlayerStatusBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(Transient, DuplicateTransient)
	class UAthenaKillsWidget_C*                   AthenaKillsWidget;                                 // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       PlayerNameText;                                    // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                PlayerTeamBGBorder;                                // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PlayerTeamText;                                    // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorTeamStatus_C*           Squadmate1;                                        // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorTeamStatus_C*           Squadmate2;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorTeamStatus_C*           Squadmate3;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDataTable*                             TextStyleSet;                                      // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AthenaSpectatorPlayerStatus(int32 EntryPoint);
	void SquadDatasChanged(const class UAthenaRemotePlayerViewData* SquadMember1, const class UAthenaRemotePlayerViewData* SquadMember2, const class UAthenaRemotePlayerViewData* SquadMember3);
	void FollowedPlayerChanged(const class AFortPlayerStateAthena* NewFollowedPlayer);
	void UpdatePlayerTeam(const int32 TeamNumber, const struct FLinearColor& TeamColor);
	void UpdatePlayerNameText(const class FText& PlayerNameText_0);
	void Construct();
	void Update_Squad_Datas(class UAthenaRemotePlayerViewData* Squad_1, class UAthenaRemotePlayerViewData* Squad_2, class UAthenaRemotePlayerViewData* Squad_3);
	void Update_Squad_Member_Data(class UAthenaRemotePlayerViewData* PlayerData, class UAthenaSpectatorTeamStatus_C* TeamStatusWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaSpectatorPlayerStatus_C">();
	}
	static class UAthenaSpectatorPlayerStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaSpectatorPlayerStatus_C>();
	}
};
static_assert(alignof(UAthenaSpectatorPlayerStatus_C) == 0x000008, "Wrong alignment on UAthenaSpectatorPlayerStatus_C");
static_assert(sizeof(UAthenaSpectatorPlayerStatus_C) == 0x000288, "Wrong size on UAthenaSpectatorPlayerStatus_C");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, UberGraphFrame) == 0x000240, "Member 'UAthenaSpectatorPlayerStatus_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, AthenaKillsWidget) == 0x000248, "Member 'UAthenaSpectatorPlayerStatus_C::AthenaKillsWidget' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, PlayerNameText) == 0x000250, "Member 'UAthenaSpectatorPlayerStatus_C::PlayerNameText' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, PlayerTeamBGBorder) == 0x000258, "Member 'UAthenaSpectatorPlayerStatus_C::PlayerTeamBGBorder' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, PlayerTeamText) == 0x000260, "Member 'UAthenaSpectatorPlayerStatus_C::PlayerTeamText' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, Squadmate1) == 0x000268, "Member 'UAthenaSpectatorPlayerStatus_C::Squadmate1' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, Squadmate2) == 0x000270, "Member 'UAthenaSpectatorPlayerStatus_C::Squadmate2' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, Squadmate3) == 0x000278, "Member 'UAthenaSpectatorPlayerStatus_C::Squadmate3' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorPlayerStatus_C, TextStyleSet) == 0x000280, "Member 'UAthenaSpectatorPlayerStatus_C::TextStyleSet' has a wrong offset!");

}

