#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorPlayerStatus

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.ExecuteUbergraph_AthenaSpectatorPlayerStatus
// 0x0070 (0x0070 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UAthenaRemotePlayerViewData*      K2Node_Event_SquadMember1;                         // 0x0008(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UAthenaRemotePlayerViewData*      K2Node_Event_SquadMember2;                         // 0x0010(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UAthenaRemotePlayerViewData*      K2Node_Event_SquadMember3;                         // 0x0018(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_PlayerNameText;                       // 0x0020(0x0018)(ConstParm)
	int32                                         K2Node_Event_TeamNumber;                           // 0x0038(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Event_TeamColor;                            // 0x003C(0x0010)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0050(0x0018)()
	const class AFortPlayerStateAthena*           K2Node_Event_NewFollowedPlayer;                    // 0x0068(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus) == 0x000070, "Wrong size on AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, EntryPoint) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_SquadMember1) == 0x000008, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_SquadMember1' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_SquadMember2) == 0x000010, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_SquadMember2' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_SquadMember3) == 0x000018, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_SquadMember3' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_PlayerNameText) == 0x000020, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_PlayerNameText' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_TeamNumber) == 0x000038, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_TeamNumber' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_TeamColor) == 0x00003C, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_TeamColor' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, CallFunc_Conv_IntToText_ReturnValue) == 0x000050, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus, K2Node_Event_NewFollowedPlayer) == 0x000068, "Member 'AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus::K2Node_Event_NewFollowedPlayer' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.SquadDatasChanged
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_SquadDatasChanged final
{
public:
	const class UAthenaRemotePlayerViewData*      SquadMember1;                                      // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UAthenaRemotePlayerViewData*      SquadMember2;                                      // 0x0008(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UAthenaRemotePlayerViewData*      SquadMember3;                                      // 0x0010(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_SquadDatasChanged) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_SquadDatasChanged");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_SquadDatasChanged) == 0x000018, "Wrong size on AthenaSpectatorPlayerStatus_C_SquadDatasChanged");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_SquadDatasChanged, SquadMember1) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_SquadDatasChanged::SquadMember1' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_SquadDatasChanged, SquadMember2) == 0x000008, "Member 'AthenaSpectatorPlayerStatus_C_SquadDatasChanged::SquadMember2' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_SquadDatasChanged, SquadMember3) == 0x000010, "Member 'AthenaSpectatorPlayerStatus_C_SquadDatasChanged::SquadMember3' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.FollowedPlayerChanged
// 0x0008 (0x0008 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged final
{
public:
	const class AFortPlayerStateAthena*           NewFollowedPlayer;                                 // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged) == 0x000008, "Wrong size on AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged, NewFollowedPlayer) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged::NewFollowedPlayer' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerTeam
// 0x0014 (0x0014 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam final
{
public:
	int32                                         TeamNumber;                                        // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           TeamColor;                                         // 0x0004(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam) == 0x000004, "Wrong alignment on AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam) == 0x000014, "Wrong size on AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam, TeamNumber) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam::TeamNumber' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam, TeamColor) == 0x000004, "Member 'AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam::TeamColor' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerNameText
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText final
{
public:
	class FText                                   PlayerNameText_0;                                  // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText) == 0x000018, "Wrong size on AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText, PlayerNameText_0) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText::PlayerNameText_0' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Update Squad Datas
// 0x0028 (0x0028 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_Update_Squad_Datas final
{
public:
	class UAthenaRemotePlayerViewData*            Squad_1;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaRemotePlayerViewData*            Squad_2;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaRemotePlayerViewData*            Squad_3;                                           // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFortPlayerStateAthena*>         SquadMembers;                                      // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_Update_Squad_Datas");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas) == 0x000028, "Wrong size on AthenaSpectatorPlayerStatus_C_Update_Squad_Datas");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas, Squad_1) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Datas::Squad_1' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas, Squad_2) == 0x000008, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Datas::Squad_2' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas, Squad_3) == 0x000010, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Datas::Squad_3' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Datas, SquadMembers) == 0x000018, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Datas::SquadMembers' has a wrong offset!");

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Update Squad Member Data
// 0x0018 (0x0018 - 0x0000)
struct AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data final
{
public:
	class UAthenaRemotePlayerViewData*            PlayerData;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaSpectatorTeamStatus_C*           TeamStatusWidget;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue1;                     // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data) == 0x000008, "Wrong alignment on AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data");
static_assert(sizeof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data) == 0x000018, "Wrong size on AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, PlayerData) == 0x000000, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::PlayerData' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, TeamStatusWidget) == 0x000008, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::TeamStatusWidget' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, Temp_bool_Variable) == 0x000010, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, CallFunc_IsValid_ReturnValue) == 0x000011, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, Temp_byte_Variable) == 0x000012, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, Temp_byte_Variable1) == 0x000013, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, K2Node_Select_Default) == 0x000014, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data, CallFunc_IsValid_ReturnValue1) == 0x000015, "Member 'AthenaSpectatorPlayerStatus_C_Update_Squad_Member_Data::CallFunc_IsValid_ReturnValue1' has a wrong offset!");

}

