#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorTeamStatus

#include "Basic.hpp"


namespace SDK::Params
{

// Function AthenaSpectatorTeamStatus.AthenaSpectatorTeamStatus_C.UpdatePlayerData
// 0x0038 (0x0038 - 0x0000)
struct AthenaSpectatorTeamStatus_C_UpdatePlayerData final
{
public:
	class UAthenaRemotePlayerViewData*            NewSource;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerStateAthena*                 CallFunc_GetPlayerState_ReturnValue;               // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPlayerName_ReturnValue;                // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0020(0x0018)()
};
static_assert(alignof(AthenaSpectatorTeamStatus_C_UpdatePlayerData) == 0x000008, "Wrong alignment on AthenaSpectatorTeamStatus_C_UpdatePlayerData");
static_assert(sizeof(AthenaSpectatorTeamStatus_C_UpdatePlayerData) == 0x000038, "Wrong size on AthenaSpectatorTeamStatus_C_UpdatePlayerData");
static_assert(offsetof(AthenaSpectatorTeamStatus_C_UpdatePlayerData, NewSource) == 0x000000, "Member 'AthenaSpectatorTeamStatus_C_UpdatePlayerData::NewSource' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorTeamStatus_C_UpdatePlayerData, CallFunc_GetPlayerState_ReturnValue) == 0x000008, "Member 'AthenaSpectatorTeamStatus_C_UpdatePlayerData::CallFunc_GetPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorTeamStatus_C_UpdatePlayerData, CallFunc_GetPlayerName_ReturnValue) == 0x000010, "Member 'AthenaSpectatorTeamStatus_C_UpdatePlayerData::CallFunc_GetPlayerName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaSpectatorTeamStatus_C_UpdatePlayerData, CallFunc_Conv_StringToText_ReturnValue) == 0x000020, "Member 'AthenaSpectatorTeamStatus_C_UpdatePlayerData::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

