#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorTeamStatus

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaSpectatorTeamStatus.AthenaSpectatorTeamStatus_C
// 0x0038 (0x0278 - 0x0240)
class UAthenaSpectatorTeamStatus_C final : public UAthenaPlayerStatusBase
{
public:
	class UAthenaSpectatorHitPointBar_C*          HealthBar;                                         // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaKillsWidget_C*                   PlayerElims;                                       // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       PlayerName;                                        // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorHitPointBar_C*          ShieldBar;                                         // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDataTable*                             TextStyleSet;                                      // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   NewEventDispatcher_0;                              // 0x0268(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void UpdatePlayerData(class UAthenaRemotePlayerViewData* NewSource);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaSpectatorTeamStatus_C">();
	}
	static class UAthenaSpectatorTeamStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaSpectatorTeamStatus_C>();
	}
};
static_assert(alignof(UAthenaSpectatorTeamStatus_C) == 0x000008, "Wrong alignment on UAthenaSpectatorTeamStatus_C");
static_assert(sizeof(UAthenaSpectatorTeamStatus_C) == 0x000278, "Wrong size on UAthenaSpectatorTeamStatus_C");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, HealthBar) == 0x000240, "Member 'UAthenaSpectatorTeamStatus_C::HealthBar' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, PlayerElims) == 0x000248, "Member 'UAthenaSpectatorTeamStatus_C::PlayerElims' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, PlayerName) == 0x000250, "Member 'UAthenaSpectatorTeamStatus_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, ShieldBar) == 0x000258, "Member 'UAthenaSpectatorTeamStatus_C::ShieldBar' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, TextStyleSet) == 0x000260, "Member 'UAthenaSpectatorTeamStatus_C::TextStyleSet' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorTeamStatus_C, NewEventDispatcher_0) == 0x000268, "Member 'UAthenaSpectatorTeamStatus_C::NewEventDispatcher_0' has a wrong offset!");

}

