#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorMatchStatus

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaSpectatorMatchStatus.AthenaSpectatorMatchStatus_C
// 0x0040 (0x0278 - 0x0238)
class UAthenaSpectatorMatchStatus_C final : public UAthenaMatchStatusBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0238(0x0008)(Transient, DuplicateTransient)
	class UAthenaGamePhaseWidget_C*               AthenaGamePhaseWidget;                             // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaPlayersLeftWidget_C*             AthenaPlayersLeftWidget;                           // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          LocationElement;                                   // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       LocationText;                                      // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MapImage;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       StormPhaseText;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AthenaSpectatorMatchStatus(int32 EntryPoint);
	void Construct();
	void UpdateMatchTimeText(const class FText& MatchTimeText);
	void UpdatePlayerLocationText(const class FText& NewLocation);
	void UpdateStormPhaseText(const class FText& SafeZonePhaseTxt);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaSpectatorMatchStatus_C">();
	}
	static class UAthenaSpectatorMatchStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaSpectatorMatchStatus_C>();
	}
};
static_assert(alignof(UAthenaSpectatorMatchStatus_C) == 0x000008, "Wrong alignment on UAthenaSpectatorMatchStatus_C");
static_assert(sizeof(UAthenaSpectatorMatchStatus_C) == 0x000278, "Wrong size on UAthenaSpectatorMatchStatus_C");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, UberGraphFrame) == 0x000238, "Member 'UAthenaSpectatorMatchStatus_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, AthenaGamePhaseWidget) == 0x000240, "Member 'UAthenaSpectatorMatchStatus_C::AthenaGamePhaseWidget' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, AthenaPlayersLeftWidget) == 0x000248, "Member 'UAthenaSpectatorMatchStatus_C::AthenaPlayersLeftWidget' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, Icon) == 0x000250, "Member 'UAthenaSpectatorMatchStatus_C::Icon' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, LocationElement) == 0x000258, "Member 'UAthenaSpectatorMatchStatus_C::LocationElement' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, LocationText) == 0x000260, "Member 'UAthenaSpectatorMatchStatus_C::LocationText' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, MapImage) == 0x000268, "Member 'UAthenaSpectatorMatchStatus_C::MapImage' has a wrong offset!");
static_assert(offsetof(UAthenaSpectatorMatchStatus_C, StormPhaseText) == 0x000270, "Member 'UAthenaSpectatorMatchStatus_C::StormPhaseText' has a wrong offset!");

}

