#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Athena_TNT

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "B_Prj_Athena_Grenade_Base_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Athena_TNT.B_Prj_Athena_TNT_C
// 0x0060 (0x07D0 - 0x0770)
class AB_Prj_Athena_TNT_C final : public AB_Prj_Athena_Grenade_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Prj_Athena_TNT_C;                 // 0x0770(0x0008)(Transient, DuplicateTransient)
	class USplineComponent*                       Spline;                                            // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 TNTBundle;                                         // 0x0780(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         MaxCookTime;                                       // 0x0788(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_78C[0x4];                                      // 0x078C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           FuseTimer;                                         // 0x0790(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         RemainingFuseTime;                                 // 0x0798(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Use_Shockwave_Based_Explosion;                     // 0x079C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79D[0x3];                                      // 0x079D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Actual_Radius;                                     // 0x07A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A4[0x4];                                      // 0x07A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           Spline_Timer;                                      // 0x07A8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bSimulationRunning;                                // 0x07B0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_7B1[0x3];                                      // 0x07B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               TargetRotation;                                    // 0x07B4(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         InterpSpeed;                                       // 0x07C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LerpDuration;                                      // 0x07C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           LerpTimer;                                         // 0x07C8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Athena_TNT(int32 EntryPoint);
	void ReceiveDestroyed();
	void Lerp();
	void RestartSimulating();
	void Event_OnVehicleDestroyed(class AActor* DestroyedActor);
	void Event_BuildingActorDied(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum);
	void BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileStopDelegate__DelegateSignature(const struct FHitResult& ImpactResult);
	void Set_Spline_Point_Locations();
	void Event_StartFuse(float Time);
	void Spline_Point_Locations(const TArray<struct FVector>* Array);
	void ReceiveBeginPlay();
	void OnStop(const struct FHitResult& Hit);
	void OnExploded(const TArray<class AActor*>& HitActors, const TArray<struct FHitResult>& HitResults);
	void OnRep_bSimulationRunning();
	void MakeOrthogonalZ(const struct FRotator& InRotation, const struct FVector& Normal, struct FRotator* OutRotation);
	void UserConstructionScript();
	void FuseEnded();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Athena_TNT_C">();
	}
	static class AB_Prj_Athena_TNT_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Athena_TNT_C>();
	}
};
static_assert(alignof(AB_Prj_Athena_TNT_C) == 0x000008, "Wrong alignment on AB_Prj_Athena_TNT_C");
static_assert(sizeof(AB_Prj_Athena_TNT_C) == 0x0007D0, "Wrong size on AB_Prj_Athena_TNT_C");
static_assert(offsetof(AB_Prj_Athena_TNT_C, UberGraphFrame_B_Prj_Athena_TNT_C) == 0x000770, "Member 'AB_Prj_Athena_TNT_C::UberGraphFrame_B_Prj_Athena_TNT_C' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, Spline) == 0x000778, "Member 'AB_Prj_Athena_TNT_C::Spline' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, TNTBundle) == 0x000780, "Member 'AB_Prj_Athena_TNT_C::TNTBundle' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, MaxCookTime) == 0x000788, "Member 'AB_Prj_Athena_TNT_C::MaxCookTime' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, FuseTimer) == 0x000790, "Member 'AB_Prj_Athena_TNT_C::FuseTimer' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, RemainingFuseTime) == 0x000798, "Member 'AB_Prj_Athena_TNT_C::RemainingFuseTime' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, Use_Shockwave_Based_Explosion) == 0x00079C, "Member 'AB_Prj_Athena_TNT_C::Use_Shockwave_Based_Explosion' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, Actual_Radius) == 0x0007A0, "Member 'AB_Prj_Athena_TNT_C::Actual_Radius' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, Spline_Timer) == 0x0007A8, "Member 'AB_Prj_Athena_TNT_C::Spline_Timer' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, bSimulationRunning) == 0x0007B0, "Member 'AB_Prj_Athena_TNT_C::bSimulationRunning' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, TargetRotation) == 0x0007B4, "Member 'AB_Prj_Athena_TNT_C::TargetRotation' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, InterpSpeed) == 0x0007C0, "Member 'AB_Prj_Athena_TNT_C::InterpSpeed' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, LerpDuration) == 0x0007C4, "Member 'AB_Prj_Athena_TNT_C::LerpDuration' has a wrong offset!");
static_assert(offsetof(AB_Prj_Athena_TNT_C, LerpTimer) == 0x0007C8, "Member 'AB_Prj_Athena_TNT_C::LerpTimer' has a wrong offset!");

}

