#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventScoreBigStat

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function EventScoreBigStat.EventScoreBigStat_C.ExecuteUbergraph_EventScoreBigStat
// 0x01F8 (0x01F8 - 0x0000)
struct EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_GoalScore;                      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFortTournamentDisplayInfo             K2Node_CustomEvent_TournamentDisplayInfo;          // 0x0008(0x0170)()
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0178(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0190(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01D0(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01E0(0x0018)()
};
static_assert(alignof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat) == 0x000008, "Wrong alignment on EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat");
static_assert(sizeof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat) == 0x0001F8, "Wrong size on EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, EntryPoint) == 0x000000, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::EntryPoint' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, K2Node_CustomEvent_GoalScore) == 0x000004, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::K2Node_CustomEvent_GoalScore' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, K2Node_CustomEvent_TournamentDisplayInfo) == 0x000008, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::K2Node_CustomEvent_TournamentDisplayInfo' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, CallFunc_Conv_IntToText_ReturnValue) == 0x000178, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, K2Node_MakeStruct_FormatArgumentData) == 0x000190, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, K2Node_MakeArray_Array) == 0x0001D0, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat, CallFunc_Format_ReturnValue) == 0x0001E0, "Member 'EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function EventScoreBigStat.EventScoreBigStat_C.SetData
// 0x0038 (0x0038 - 0x0000)
struct EventScoreBigStat_C_SetData final
{
public:
	class FText                                   Label;                                             // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         Value;                                             // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0020(0x0018)()
};
static_assert(alignof(EventScoreBigStat_C_SetData) == 0x000008, "Wrong alignment on EventScoreBigStat_C_SetData");
static_assert(sizeof(EventScoreBigStat_C_SetData) == 0x000038, "Wrong size on EventScoreBigStat_C_SetData");
static_assert(offsetof(EventScoreBigStat_C_SetData, Label) == 0x000000, "Member 'EventScoreBigStat_C_SetData::Label' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_SetData, Value) == 0x000018, "Member 'EventScoreBigStat_C_SetData::Value' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_SetData, CallFunc_Conv_IntToText_ReturnValue) == 0x000020, "Member 'EventScoreBigStat_C_SetData::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

// Function EventScoreBigStat.EventScoreBigStat_C.SetGoalScore
// 0x0178 (0x0178 - 0x0000)
struct EventScoreBigStat_C_SetGoalScore final
{
public:
	int32                                         GoalScore;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortTournamentDisplayInfo             TournamentDisplayInfo;                             // 0x0008(0x0170)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(EventScoreBigStat_C_SetGoalScore) == 0x000008, "Wrong alignment on EventScoreBigStat_C_SetGoalScore");
static_assert(sizeof(EventScoreBigStat_C_SetGoalScore) == 0x000178, "Wrong size on EventScoreBigStat_C_SetGoalScore");
static_assert(offsetof(EventScoreBigStat_C_SetGoalScore, GoalScore) == 0x000000, "Member 'EventScoreBigStat_C_SetGoalScore::GoalScore' has a wrong offset!");
static_assert(offsetof(EventScoreBigStat_C_SetGoalScore, TournamentDisplayInfo) == 0x000008, "Member 'EventScoreBigStat_C_SetGoalScore::TournamentDisplayInfo' has a wrong offset!");

}

