#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventScoreBigStat

#include "Basic.hpp"

#include "EventScoreBigStat_classes.hpp"
#include "EventScoreBigStat_parameters.hpp"


namespace SDK
{

// Function EventScoreBigStat.EventScoreBigStat_C.ExecuteUbergraph_EventScoreBigStat
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEventScoreBigStat_C::ExecuteUbergraph_EventScoreBigStat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EventScoreBigStat_C", "ExecuteUbergraph_EventScoreBigStat");

	Params::EventScoreBigStat_C_ExecuteUbergraph_EventScoreBigStat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EventScoreBigStat.EventScoreBigStat_C.SetData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Label                                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEventScoreBigStat_C::SetData(const class FText& Label, int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EventScoreBigStat_C", "SetData");

	Params::EventScoreBigStat_C_SetData Parms{};

	Parms.Label = std::move(Label);
	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EventScoreBigStat.EventScoreBigStat_C.SetGoalScore
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   GoalScore                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFortTournamentDisplayInfo       TournamentDisplayInfo                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UEventScoreBigStat_C::SetGoalScore(int32 GoalScore, const struct FFortTournamentDisplayInfo& TournamentDisplayInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EventScoreBigStat_C", "SetGoalScore");

	Params::EventScoreBigStat_C_SetGoalScore Parms{};

	Parms.GoalScore = GoalScore;
	Parms.TournamentDisplayInfo = std::move(TournamentDisplayInfo);

	UObject::ProcessEvent(Func, &Parms);
}

}

