#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventScoreBigStat

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EventScoreBigStat.EventScoreBigStat_C
// 0x0028 (0x0250 - 0x0228)
class UEventScoreBigStat_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(Transient, DuplicateTransient)
	class UCommonBorder*                          CommonBorder_GoalScore;                            // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         RichTextBlock_GoalScore;                           // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       StatLabelText;                                     // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       StatValueText;                                     // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_EventScoreBigStat(int32 EntryPoint);
	void SetData(const class FText& Label, int32 Value);
	void SetGoalScore(int32 GoalScore, const struct FFortTournamentDisplayInfo& TournamentDisplayInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EventScoreBigStat_C">();
	}
	static class UEventScoreBigStat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEventScoreBigStat_C>();
	}
};
static_assert(alignof(UEventScoreBigStat_C) == 0x000008, "Wrong alignment on UEventScoreBigStat_C");
static_assert(sizeof(UEventScoreBigStat_C) == 0x000250, "Wrong size on UEventScoreBigStat_C");
static_assert(offsetof(UEventScoreBigStat_C, UberGraphFrame) == 0x000228, "Member 'UEventScoreBigStat_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UEventScoreBigStat_C, CommonBorder_GoalScore) == 0x000230, "Member 'UEventScoreBigStat_C::CommonBorder_GoalScore' has a wrong offset!");
static_assert(offsetof(UEventScoreBigStat_C, RichTextBlock_GoalScore) == 0x000238, "Member 'UEventScoreBigStat_C::RichTextBlock_GoalScore' has a wrong offset!");
static_assert(offsetof(UEventScoreBigStat_C, StatLabelText) == 0x000240, "Member 'UEventScoreBigStat_C::StatLabelText' has a wrong offset!");
static_assert(offsetof(UEventScoreBigStat_C, StatValueText) == 0x000248, "Member 'UEventScoreBigStat_C::StatValueText' has a wrong offset!");

}

