#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontEnd

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FrontEnd.FrontEnd_C
// 0x00D8 (0x0438 - 0x0360)
class UFrontEnd_C final : public UFortUIStateWidget_Frontend
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(Transient, DuplicateTransient)
	class UBottomBarWidget_C*                     BottomBar;                                         // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                BottomBarSizedSpacer;                              // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      ButtonPTT;                                         // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      ButtonToggleChat;                                  // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UChatWidget_C*                          ChatWidget;                                        // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                MainAreaDarken;                                    // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonWidgetStack*                     MainContentStack;                                  // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBoxPTT;                                        // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTopBar_C*                              TopBar;                                            // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                TopBarSizedSpacer;                                 // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          PlayedCurrentEventMovie;                           // 0x03B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          StartedPlayingVideo;                               // 0x03B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BA[0x6];                                      // 0x03BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         CampaignScriptedActions;                           // 0x03C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UClass*>                         PostSubgameScriptedActions;                        // 0x03D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	bool                                          HasBeenDeferringSurvivorSquadAutoSlottedNotification; // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E1[0x7];                                      // 0x03E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<EFortStoreState>                         StoreStatesThatDeferSurvivorSquadAutoSlottingNotifications; // 0x03E8(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)

public:
	void ExecuteUbergraph_FrontEnd(int32 EntryPoint);
	void HandleStoreStateChanged(EFortStoreState NewStoreState);
	void HandleSurvivorSquadsAutoSlotted();
	void OnMovieFinished();
	void On_Social_Import_Closed();
	void OnEnterState(EFortUIState PreviousUIState);
	void HandleQuestsGranted(const TArray<class UFortQuestItem*>& Quests);
	void On_Can_PTT();
	void BndEvt__ButtonPTT_K2Node_ComponentBoundEvent_138_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void BndEvt__ButtonToggleChat_K2Node_ComponentBoundEvent_39_CommonSelectedStateChanged__DelegateSignature(class UCommonButton* Button, bool Selected);
	void HandleQuestsCompleted(const TArray<class UFortQuestItem*>& Quests);
	void BndEvt__ButtonToggleChat_K2Node_ComponentBoundEvent_6_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void Loading_Screen_Changed(bool IsVisible_0);
	void Construct();
	void RequestOpenSocialMenu();
	void HandleClientEvent_NotPlayingEventMovie(class UObject* EventSource, class UObject* EventFocus, const struct FFortClientEvent& ClientEvent);
	void HandleClientEvent_EventMovieFinishedPlaying(class UObject* EventSource, class UObject* EventFocus, const struct FFortClientEvent& ClientEvent);
	void OnFrontEndVisibilityUpdated(bool bHideHeader, bool bHideFooter, bool bHideChatWidget);
	void HandleClientEvent_FinishedModalWindows(class UObject* EventSource, class UObject* EventFocus, const struct FFortClientEvent& ClientEvent);
	void DailyRewardsTokenGranted();
	void Destruct();
	void OnExitState(EFortUIState NextUIState);
	void PushContentWidgetInternal(class UWidget* Widget, const struct FContentPushState& State);
	void HandleLobbyDisconnected();
	struct FEventReply On_MainAreaDarken_MouseButtonUp(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	void HandleMainMenuStateChanged(bool Index_0);
	void RegisterScriptedActions(EFortUIState InPreviousUIState);
	void SetHeaderVisibility(bool Visible);
	void SetFooterVisibility(bool Visible);
	void HandleEnterFrontend(EFortUIState UIState);
	void BindDelegates();
	void HandleQuestRewardClaimed(class UFortQuestItem* Quest, TArray<struct FFortItemInstanceQuantityPair>& Rewards);
	class UWidget* PopContentWidgetInternal(const struct FContentPushState& State);
	void HandlePopContentStackOp();
	void UnbindDelegates();
	void HandleWidgetStackChanged(class UWidget* Widget, int32 ActiveWidgetIndex);
	void GetActiveTab(class FName* ActiveTab);
	void InitForSubGame();
	void SetChatWidgetVisibility(bool Visible);
	void UpdateVisibilityState(bool HideHeader, bool HideFooter, bool HideChat);
	void NeedsToPlayEventMovie(bool* NeedsToPlayEventMovie_0);
	void PlayEventMovieIfNecessary(bool* PlayingEventMovie);
	void SetOverlayTitleBarVisibility(bool Visible);
	void UpdatePttVisibility(EPTTState PTTState);
	void InitChatVisibilityButton();
	void PlayTrailer();
	void IsPrototyping(bool* Result);
	bool IsCampaign();
	void RegisterPostSubGameScriptedActions();
	void SetupSafeZones(class UAthenaTabsScreen_C* AthenaTabsScreen);
	void QueueSurvivorSquadsAutoSlottedNotification();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FrontEnd_C">();
	}
	static class UFrontEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFrontEnd_C>();
	}
};
static_assert(alignof(UFrontEnd_C) == 0x000008, "Wrong alignment on UFrontEnd_C");
static_assert(sizeof(UFrontEnd_C) == 0x000438, "Wrong size on UFrontEnd_C");
static_assert(offsetof(UFrontEnd_C, UberGraphFrame) == 0x000360, "Member 'UFrontEnd_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, BottomBar) == 0x000368, "Member 'UFrontEnd_C::BottomBar' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, BottomBarSizedSpacer) == 0x000370, "Member 'UFrontEnd_C::BottomBarSizedSpacer' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, ButtonPTT) == 0x000378, "Member 'UFrontEnd_C::ButtonPTT' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, ButtonToggleChat) == 0x000380, "Member 'UFrontEnd_C::ButtonToggleChat' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, ChatWidget) == 0x000388, "Member 'UFrontEnd_C::ChatWidget' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, MainAreaDarken) == 0x000390, "Member 'UFrontEnd_C::MainAreaDarken' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, MainContentStack) == 0x000398, "Member 'UFrontEnd_C::MainContentStack' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, SizeBoxPTT) == 0x0003A0, "Member 'UFrontEnd_C::SizeBoxPTT' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, TopBar) == 0x0003A8, "Member 'UFrontEnd_C::TopBar' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, TopBarSizedSpacer) == 0x0003B0, "Member 'UFrontEnd_C::TopBarSizedSpacer' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, PlayedCurrentEventMovie) == 0x0003B8, "Member 'UFrontEnd_C::PlayedCurrentEventMovie' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, StartedPlayingVideo) == 0x0003B9, "Member 'UFrontEnd_C::StartedPlayingVideo' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, CampaignScriptedActions) == 0x0003C0, "Member 'UFrontEnd_C::CampaignScriptedActions' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, PostSubgameScriptedActions) == 0x0003D0, "Member 'UFrontEnd_C::PostSubgameScriptedActions' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, HasBeenDeferringSurvivorSquadAutoSlottedNotification) == 0x0003E0, "Member 'UFrontEnd_C::HasBeenDeferringSurvivorSquadAutoSlottedNotification' has a wrong offset!");
static_assert(offsetof(UFrontEnd_C, StoreStatesThatDeferSurvivorSquadAutoSlottingNotifications) == 0x0003E8, "Member 'UFrontEnd_C::StoreStatesThatDeferSurvivorSquadAutoSlottingNotifications' has a wrong offset!");

}

