#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCL_TNT_Fuse_Projectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCL_TNT_Fuse_Projectile.GCL_TNT_Fuse_Projectile_C
// 0x0090 (0x0928 - 0x0898)
class AGCL_TNT_Fuse_Projectile_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0898(0x0008)(Transient, DuplicateTransient)
	float                                         Fuse_Movement_Material_Flash_74AFF49A4CEE87DDE4FCD785AA920130; // 0x08A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Fuse_Movement_Death_Warning_74AFF49A4CEE87DDE4FCD785AA920130; // 0x08A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Fuse_Movement_Lerp_Control_74AFF49A4CEE87DDE4FCD785AA920130; // 0x08A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Fuse_Movement__Direction_74AFF49A4CEE87DDE4FCD785AA920130; // 0x08AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8AD[0x3];                                      // 0x08AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Fuse_Movement;                                     // 0x08B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FuseDuration;                                      // 0x08B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FuseElapsedTime;                                   // 0x08BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AB_Prj_Athena_TNT_C*                    Projectile;                                        // 0x08C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Death_FX;                                          // 0x08C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Flare_Size;                                        // 0x08D0(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PSysSplineLoca;                                    // 0x08DC(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               PSysSplineRot;                                     // 0x08E8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         PSys_Opacity;                                      // 0x08F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PSys_Color;                                        // 0x08F8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Psys_Size;                                         // 0x0904(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               LoopingParticle;                                   // 0x0910(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Looping_Audio;                                     // 0x0918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        DeathAudio;                                        // 0x0920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GCL_TNT_Fuse_Projectile(int32 EntryPoint);
	void Control_Fuse_Particles();
	void OnRemoval(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance);
	void OnLoopingStart(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents);
	void Fuse_Movement__Particle_Swap__EventFunc();
	void Fuse_Movement__UpdateFunc();
	void Fuse_Movement__FinishedFunc();
	void UserConstructionScript();
	void Spline_Setup(float Alpha, struct FVector* Spline_Location);
	void Warning_System_Setup(float Warning, float Flash, struct FVector* Material_Emissive, float* Opacity, struct FVector* Color, struct FVector* Size);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCL_TNT_Fuse_Projectile_C">();
	}
	static class AGCL_TNT_Fuse_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCL_TNT_Fuse_Projectile_C>();
	}
};
static_assert(alignof(AGCL_TNT_Fuse_Projectile_C) == 0x000008, "Wrong alignment on AGCL_TNT_Fuse_Projectile_C");
static_assert(sizeof(AGCL_TNT_Fuse_Projectile_C) == 0x000928, "Wrong size on AGCL_TNT_Fuse_Projectile_C");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, UberGraphFrame) == 0x000898, "Member 'AGCL_TNT_Fuse_Projectile_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Fuse_Movement_Material_Flash_74AFF49A4CEE87DDE4FCD785AA920130) == 0x0008A0, "Member 'AGCL_TNT_Fuse_Projectile_C::Fuse_Movement_Material_Flash_74AFF49A4CEE87DDE4FCD785AA920130' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Fuse_Movement_Death_Warning_74AFF49A4CEE87DDE4FCD785AA920130) == 0x0008A4, "Member 'AGCL_TNT_Fuse_Projectile_C::Fuse_Movement_Death_Warning_74AFF49A4CEE87DDE4FCD785AA920130' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Fuse_Movement_Lerp_Control_74AFF49A4CEE87DDE4FCD785AA920130) == 0x0008A8, "Member 'AGCL_TNT_Fuse_Projectile_C::Fuse_Movement_Lerp_Control_74AFF49A4CEE87DDE4FCD785AA920130' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Fuse_Movement__Direction_74AFF49A4CEE87DDE4FCD785AA920130) == 0x0008AC, "Member 'AGCL_TNT_Fuse_Projectile_C::Fuse_Movement__Direction_74AFF49A4CEE87DDE4FCD785AA920130' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Fuse_Movement) == 0x0008B0, "Member 'AGCL_TNT_Fuse_Projectile_C::Fuse_Movement' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, FuseDuration) == 0x0008B8, "Member 'AGCL_TNT_Fuse_Projectile_C::FuseDuration' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, FuseElapsedTime) == 0x0008BC, "Member 'AGCL_TNT_Fuse_Projectile_C::FuseElapsedTime' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Projectile) == 0x0008C0, "Member 'AGCL_TNT_Fuse_Projectile_C::Projectile' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Death_FX) == 0x0008C8, "Member 'AGCL_TNT_Fuse_Projectile_C::Death_FX' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Flare_Size) == 0x0008D0, "Member 'AGCL_TNT_Fuse_Projectile_C::Flare_Size' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, PSysSplineLoca) == 0x0008DC, "Member 'AGCL_TNT_Fuse_Projectile_C::PSysSplineLoca' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, PSysSplineRot) == 0x0008E8, "Member 'AGCL_TNT_Fuse_Projectile_C::PSysSplineRot' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, PSys_Opacity) == 0x0008F4, "Member 'AGCL_TNT_Fuse_Projectile_C::PSys_Opacity' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, PSys_Color) == 0x0008F8, "Member 'AGCL_TNT_Fuse_Projectile_C::PSys_Color' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Psys_Size) == 0x000904, "Member 'AGCL_TNT_Fuse_Projectile_C::Psys_Size' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, LoopingParticle) == 0x000910, "Member 'AGCL_TNT_Fuse_Projectile_C::LoopingParticle' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, Looping_Audio) == 0x000918, "Member 'AGCL_TNT_Fuse_Projectile_C::Looping_Audio' has a wrong offset!");
static_assert(offsetof(AGCL_TNT_Fuse_Projectile_C, DeathAudio) == 0x000920, "Member 'AGCL_TNT_Fuse_Projectile_C::DeathAudio' has a wrong offset!");

}

