#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshNetwork

#include "Basic.hpp"

#include "MeshNetwork_structs.hpp"


namespace SDK::Params
{

// Function MeshNetwork.MeshNetworkComponent.GetMeshNetworkNodeType
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkComponent_GetMeshNetworkNodeType final
{
public:
	EMeshNetworkNodeType                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(MeshNetworkComponent_GetMeshNetworkNodeType) == 0x000001, "Wrong alignment on MeshNetworkComponent_GetMeshNetworkNodeType");
static_assert(sizeof(MeshNetworkComponent_GetMeshNetworkNodeType) == 0x000001, "Wrong size on MeshNetworkComponent_GetMeshNetworkNodeType");
static_assert(offsetof(MeshNetworkComponent_GetMeshNetworkNodeType, ReturnValue) == 0x000000, "Member 'MeshNetworkComponent_GetMeshNetworkNodeType::ReturnValue' has a wrong offset!");

// Function MeshNetwork.MeshNetworkSubsystem.GetConnectedToRoot
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkSubsystem_GetConnectedToRoot final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(MeshNetworkSubsystem_GetConnectedToRoot) == 0x000001, "Wrong alignment on MeshNetworkSubsystem_GetConnectedToRoot");
static_assert(sizeof(MeshNetworkSubsystem_GetConnectedToRoot) == 0x000001, "Wrong size on MeshNetworkSubsystem_GetConnectedToRoot");
static_assert(offsetof(MeshNetworkSubsystem_GetConnectedToRoot, ReturnValue) == 0x000000, "Member 'MeshNetworkSubsystem_GetConnectedToRoot::ReturnValue' has a wrong offset!");

// Function MeshNetwork.MeshNetworkSubsystem.GetMeshNetworkNodeType
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkSubsystem_GetMeshNetworkNodeType final
{
public:
	EMeshNetworkNodeType                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(MeshNetworkSubsystem_GetMeshNetworkNodeType) == 0x000001, "Wrong alignment on MeshNetworkSubsystem_GetMeshNetworkNodeType");
static_assert(sizeof(MeshNetworkSubsystem_GetMeshNetworkNodeType) == 0x000001, "Wrong size on MeshNetworkSubsystem_GetMeshNetworkNodeType");
static_assert(offsetof(MeshNetworkSubsystem_GetMeshNetworkNodeType, ReturnValue) == 0x000000, "Member 'MeshNetworkSubsystem_GetMeshNetworkNodeType::ReturnValue' has a wrong offset!");

}

