#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerPawn_Athena_Generic

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "PlayerPawn_Athena_Generic_Parent_classes.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PlayerPawn_Athena_Generic.PlayerPawn_Athena_Generic_C
// 0x02F0 (0x29C0 - 0x26D0)
class APlayerPawn_Athena_Generic_C : public APlayerPawn_Athena_Generic_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PlayerPawn_Athena_Generic_C;        // 0x26D0(0x0008)(Transient, DuplicateTransient)
	class UAudioComponent*                        InAirAudio;                                        // 0x26D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_In_Water;                            // 0x26E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Slide_Land;                          // 0x26E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Run_Land;                            // 0x26F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Walk_Land;                           // 0x26F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_WaterInteraction_FX;                        // 0x2700(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               AnimTrailPS;                                       // 0x2708(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               HitDamageParticles;                                // 0x2710(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         CapsuleFadeTL_RemoveShadow_3B9EF0C6475C736BCC63B3852E8CAE42; // 0x2718(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            CapsuleFadeTL__Direction_3B9EF0C6475C736BCC63B3852E8CAE42; // 0x271C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271D[0x3];                                     // 0x271D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     CapsuleFadeTL;                                     // 0x2720(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerHealthDamageDirection;          // 0x2728(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerHealthDamage;                   // 0x2730(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerShieldDamageDirection;          // 0x2738(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerShieldDamage;                   // 0x2740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Run_Particle_Activate_Speed;                       // 0x2748(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Walk_Dust_Activate_Speed;                          // 0x274C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Walk_Particle_Reset_Speed;                         // 0x2750(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanSpawnRunKickupFX_;                              // 0x2754(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanSpawnWalkKickupFX_;                             // 0x2755(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanSpawnDustLandFX_;                               // 0x2756(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsInWater;                                         // 0x2757(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               RunWalkParticleRotation;                           // 0x2758(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsNinjaInShadowStance_;                            // 0x2764(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2765[0x3];                                     // 0x2765(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  GameplayTagsForHitByHuskMeleeSound;                // 0x2768(0x0020)(Edit, BlueprintVisible)
	int32                                         WaterCounter;                                      // 0x2788(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Tick_Delta_Seconds;                                // 0x278C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_Impact;                               // 0x2790(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_Destroyed;                            // 0x2798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_FullyCharged;                         // 0x27A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_StartRecharge;                        // 0x27A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_GameplayCueDamageShielded;                      // 0x27B0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          LatestDamageIsShieldDamage;                        // 0x27D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_27D1[0x3];                                     // 0x27D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Damage_Taken;                                      // 0x27D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Last_Shield_Damage_Time;                           // 0x27D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27DC[0x4];                                     // 0x27DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPoseableMeshComponent*                 NewVar_1;                                          // 0x27E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          BodyValid;                                         // 0x27E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          BackpackValid;                                     // 0x27E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HatValid;                                          // 0x27EA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          FaceValid;                                         // 0x27EB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CharmValid;                                        // 0x27EC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HeadValid;                                         // 0x27ED(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_27EE[0x2];                                     // 0x27EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        P_DBNOResurrect;                                   // 0x27F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DBNOResurrectSound;                                // 0x27F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Effect_Player_LandedDust;                          // 0x2800(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       TempArray;                                         // 0x2808(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class USceneComponent*                        Sound_Player_Hit;                                  // 0x2818(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   DamageForceFeedback;                               // 0x2820(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Effect_Player_Landed_WindVector_P;                 // 0x2828(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 SpeechBubbleWidgetClass;                           // 0x2830(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   LastSpeechText;                                    // 0x2838(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 DamageCameraShake;                                 // 0x2850(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseAnimTrailsNotifies;                             // 0x2858(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2859[0x3];                                     // 0x2859(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Time_when_you_ll_be_able_to_splash_again;          // 0x285C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CurrentWaterMeshActor;                             // 0x2860(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             WaterTraceHitLocation;                             // 0x2868(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                StableVelocityVector;                              // 0x28F0(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28FC[0x4];                                     // 0x28FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        PlayerRunTemplate_Ground;                          // 0x2900(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerWalkTemplate_Ground;                         // 0x2908(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerRunTemplate_Water;                           // 0x2910(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerWalkTemplate_Water;                          // 0x2918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          Pawn_Charm_Skeletal_Mesh;                          // 0x2920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               AnimTrailsPS_Ref;                                  // 0x2928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     WeaponMaterialOverride;                            // 0x2930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TickWaterLevel;                                    // 0x2938(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2939[0x7];                                     // 0x2939(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextureRenderTarget2D*                 WetnessDepthTexture;                               // 0x2940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               WaterLevelMID;                                     // 0x2948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               WaterDecayMID;                                     // 0x2950(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Was_RTT_Enabled_Var_Set;                           // 0x2958(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Is_RTT_Enabled;                                    // 0x2959(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_295A[0x2];                                     // 0x295A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SlideAudioIntensity;                               // 0x295C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         StartingMinCapsuleShadowVis;                       // 0x2960(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsShielded;                                        // 0x2964(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2965[0x3];                                     // 0x2965(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InstigatorCheckDistanceSqrd;                       // 0x2968(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_296C[0x4];                                     // 0x296C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        SlidingAudio_Inst;                                 // 0x2970(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SlideDustActivateSpeed;                            // 0x2978(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanSpawnSlideKickupFX_;                            // 0x297C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_297D[0x3];                                     // 0x297D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        Effect_Player_ShieldActivate;                      // 0x2980(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Effect_PLayer_ShieldBreak;                         // 0x2988(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GhostMode;                                         // 0x2990(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2991[0x3];                                     // 0x2991(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InAirAudioScalar;                                  // 0x2994(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        InAirAudio_Inst;                                   // 0x2998(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InAirAudioInterpSpeed;                             // 0x29A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PawnSpeedAudioMin;                                 // 0x29A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PawnSpeedAudioMax;                                 // 0x29A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29AC[0x4];                                     // 0x29AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             Sound_InAirLoop1P;                                 // 0x29B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_InAirLoop3P;                                 // 0x29B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PlayerPawn_Athena_Generic(int32 EntryPoint);
	void GameplayCue_Shield_Reapplied(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Shield_FullyCharged(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Shield_Destroyed(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Damage_Shielded(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Shield_PotionConsumed(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void OnLand_CE();
	void OnSlidingStateChanged(bool bNewSlidingState);
	void OnPawnLODChanged(int32 NewLOD);
	void ReceiveTick(float DeltaSeconds);
	void GameplayCue_Abilities_SpookyMist_Loop(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Abilities_Death_FadeCapsule_Athena(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void OnSignificantTick(float Significance);
	void AnimTrailsDisable();
	void AnimTrailsSetup(class UParticleSystem* ParticleSystemReference, class FName FirstSocketName, class FName SecondSocketName, float Width);
	void AnimTrailsNotify(bool bActive);
	void FadeOutCapsuleShadow();
	void BindOnDestroyed();
	void CharacterDestroyed(class AActor* DestroyedActor);
	void Entered_WaterVolume();
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void ReceiveDestroyed();
	void GameplayCue_Abilities_Activation_DBNOResurrect(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Abilities_Activation_Generic_HarvestBuff_Tier2(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Abilities_Activation_Generic_HarvestBuff_Tier1(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void OnCharacterPartsReinitialized();
	void FootStepRight();
	void FootStepLeft();
	void OnWeaponEquipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnLanded(const struct FHitResult& Hit);
	void OnDamagePlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void MeleeSwingLeft();
	void MeleeSwingRight();
	void CapsuleFadeTL__UpdateFunc();
	void CapsuleFadeTL__FinishedFunc();
	void UserConstructionScript();
	void Create_and_Duplicate_Effect_Skeletal_Meshes_Parent(EFortCustomPartType BodyType, class USkeletalMeshComponent*& DuplicatedSkeletalMeshComponent, class UMaterialInterface* Material_to_Apply, TArray<class UMaterialInstanceDynamic*>& Empty_MID_Array, int32 TranslucentSortPriority);
	void SlaveAMeshToTheBody(class USkeletalMeshComponent* Mesh_0, class USkeletalMeshComponent* Master);
	void Create_and_Duplicate_Effect_Poseable_Skeletal_Mesh(EFortCustomPartType BodyType, class UMaterialInterface* Material_to_Apply, TArray<class UMaterialInstanceDynamic*>& Empty_MID_Array, int32 TranslucentSortPriority, class UPoseableMeshComponent*& PoseableMesh);
	void DisableWaterLevelTick();
	void Are_the_wind_and_water_RTT_passes_enabled(bool* NewParam);
	void SetSlidingAudioEnabled(bool Enabled);
	void SetSlidingFXEnabled(bool Enabled);
	void GetHitPoint_FXLocation(class AActor* Object, struct FVector* OutputLocation);
	void Melee_Effect_Color(struct FVector* Melee_Color_Set);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerPawn_Athena_Generic_C">();
	}
	static class APlayerPawn_Athena_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlayerPawn_Athena_Generic_C>();
	}
};
static_assert(alignof(APlayerPawn_Athena_Generic_C) == 0x000010, "Wrong alignment on APlayerPawn_Athena_Generic_C");
static_assert(sizeof(APlayerPawn_Athena_Generic_C) == 0x0029C0, "Wrong size on APlayerPawn_Athena_Generic_C");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, UberGraphFrame_PlayerPawn_Athena_Generic_C) == 0x0026D0, "Member 'APlayerPawn_Athena_Generic_C::UberGraphFrame_PlayerPawn_Athena_Generic_C' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, InAirAudio) == 0x0026D8, "Member 'APlayerPawn_Athena_Generic_C::InAirAudio' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_In_Water) == 0x0026E0, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_In_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_Slide_Land) == 0x0026E8, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_Slide_Land' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_Run_Land) == 0x0026F0, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_Run_Land' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_Walk_Land) == 0x0026F8, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_Walk_Land' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_WaterInteraction_FX) == 0x002700, "Member 'APlayerPawn_Athena_Generic_C::Effect_WaterInteraction_FX' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, AnimTrailPS) == 0x002708, "Member 'APlayerPawn_Athena_Generic_C::AnimTrailPS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, HitDamageParticles) == 0x002710, "Member 'APlayerPawn_Athena_Generic_C::HitDamageParticles' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CapsuleFadeTL_RemoveShadow_3B9EF0C6475C736BCC63B3852E8CAE42) == 0x002718, "Member 'APlayerPawn_Athena_Generic_C::CapsuleFadeTL_RemoveShadow_3B9EF0C6475C736BCC63B3852E8CAE42' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CapsuleFadeTL__Direction_3B9EF0C6475C736BCC63B3852E8CAE42) == 0x00271C, "Member 'APlayerPawn_Athena_Generic_C::CapsuleFadeTL__Direction_3B9EF0C6475C736BCC63B3852E8CAE42' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CapsuleFadeTL) == 0x002720, "Member 'APlayerPawn_Athena_Generic_C::CapsuleFadeTL' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, ScreenEffect_PlayerHealthDamageDirection) == 0x002728, "Member 'APlayerPawn_Athena_Generic_C::ScreenEffect_PlayerHealthDamageDirection' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, ScreenEffect_PlayerHealthDamage) == 0x002730, "Member 'APlayerPawn_Athena_Generic_C::ScreenEffect_PlayerHealthDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, ScreenEffect_PlayerShieldDamageDirection) == 0x002738, "Member 'APlayerPawn_Athena_Generic_C::ScreenEffect_PlayerShieldDamageDirection' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, ScreenEffect_PlayerShieldDamage) == 0x002740, "Member 'APlayerPawn_Athena_Generic_C::ScreenEffect_PlayerShieldDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Run_Particle_Activate_Speed) == 0x002748, "Member 'APlayerPawn_Athena_Generic_C::Run_Particle_Activate_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Walk_Dust_Activate_Speed) == 0x00274C, "Member 'APlayerPawn_Athena_Generic_C::Walk_Dust_Activate_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Walk_Particle_Reset_Speed) == 0x002750, "Member 'APlayerPawn_Athena_Generic_C::Walk_Particle_Reset_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CanSpawnRunKickupFX_) == 0x002754, "Member 'APlayerPawn_Athena_Generic_C::CanSpawnRunKickupFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CanSpawnWalkKickupFX_) == 0x002755, "Member 'APlayerPawn_Athena_Generic_C::CanSpawnWalkKickupFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CanSpawnDustLandFX_) == 0x002756, "Member 'APlayerPawn_Athena_Generic_C::CanSpawnDustLandFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, IsInWater) == 0x002757, "Member 'APlayerPawn_Athena_Generic_C::IsInWater' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, RunWalkParticleRotation) == 0x002758, "Member 'APlayerPawn_Athena_Generic_C::RunWalkParticleRotation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, IsNinjaInShadowStance_) == 0x002764, "Member 'APlayerPawn_Athena_Generic_C::IsNinjaInShadowStance_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, GameplayTagsForHitByHuskMeleeSound) == 0x002768, "Member 'APlayerPawn_Athena_Generic_C::GameplayTagsForHitByHuskMeleeSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WaterCounter) == 0x002788, "Member 'APlayerPawn_Athena_Generic_C::WaterCounter' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Tick_Delta_Seconds) == 0x00278C, "Member 'APlayerPawn_Athena_Generic_C::Tick_Delta_Seconds' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_Shield_Impact) == 0x002790, "Member 'APlayerPawn_Athena_Generic_C::Sound_Shield_Impact' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_Shield_Destroyed) == 0x002798, "Member 'APlayerPawn_Athena_Generic_C::Sound_Shield_Destroyed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_Shield_FullyCharged) == 0x0027A0, "Member 'APlayerPawn_Athena_Generic_C::Sound_Shield_FullyCharged' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_Shield_StartRecharge) == 0x0027A8, "Member 'APlayerPawn_Athena_Generic_C::Sound_Shield_StartRecharge' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, TC_GameplayCueDamageShielded) == 0x0027B0, "Member 'APlayerPawn_Athena_Generic_C::TC_GameplayCueDamageShielded' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, LatestDamageIsShieldDamage) == 0x0027D0, "Member 'APlayerPawn_Athena_Generic_C::LatestDamageIsShieldDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Damage_Taken) == 0x0027D4, "Member 'APlayerPawn_Athena_Generic_C::Damage_Taken' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Last_Shield_Damage_Time) == 0x0027D8, "Member 'APlayerPawn_Athena_Generic_C::Last_Shield_Damage_Time' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, NewVar_1) == 0x0027E0, "Member 'APlayerPawn_Athena_Generic_C::NewVar_1' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, BodyValid) == 0x0027E8, "Member 'APlayerPawn_Athena_Generic_C::BodyValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, BackpackValid) == 0x0027E9, "Member 'APlayerPawn_Athena_Generic_C::BackpackValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, HatValid) == 0x0027EA, "Member 'APlayerPawn_Athena_Generic_C::HatValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, FaceValid) == 0x0027EB, "Member 'APlayerPawn_Athena_Generic_C::FaceValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CharmValid) == 0x0027EC, "Member 'APlayerPawn_Athena_Generic_C::CharmValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, HeadValid) == 0x0027ED, "Member 'APlayerPawn_Athena_Generic_C::HeadValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, P_DBNOResurrect) == 0x0027F0, "Member 'APlayerPawn_Athena_Generic_C::P_DBNOResurrect' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, DBNOResurrectSound) == 0x0027F8, "Member 'APlayerPawn_Athena_Generic_C::DBNOResurrectSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_LandedDust) == 0x002800, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_LandedDust' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, TempArray) == 0x002808, "Member 'APlayerPawn_Athena_Generic_C::TempArray' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_Player_Hit) == 0x002818, "Member 'APlayerPawn_Athena_Generic_C::Sound_Player_Hit' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, DamageForceFeedback) == 0x002820, "Member 'APlayerPawn_Athena_Generic_C::DamageForceFeedback' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_Landed_WindVector_P) == 0x002828, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_Landed_WindVector_P' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, SpeechBubbleWidgetClass) == 0x002830, "Member 'APlayerPawn_Athena_Generic_C::SpeechBubbleWidgetClass' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, LastSpeechText) == 0x002838, "Member 'APlayerPawn_Athena_Generic_C::LastSpeechText' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, DamageCameraShake) == 0x002850, "Member 'APlayerPawn_Athena_Generic_C::DamageCameraShake' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, UseAnimTrailsNotifies) == 0x002858, "Member 'APlayerPawn_Athena_Generic_C::UseAnimTrailsNotifies' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Time_when_you_ll_be_able_to_splash_again) == 0x00285C, "Member 'APlayerPawn_Athena_Generic_C::Time_when_you_ll_be_able_to_splash_again' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CurrentWaterMeshActor) == 0x002860, "Member 'APlayerPawn_Athena_Generic_C::CurrentWaterMeshActor' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WaterTraceHitLocation) == 0x002868, "Member 'APlayerPawn_Athena_Generic_C::WaterTraceHitLocation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, StableVelocityVector) == 0x0028F0, "Member 'APlayerPawn_Athena_Generic_C::StableVelocityVector' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PlayerRunTemplate_Ground) == 0x002900, "Member 'APlayerPawn_Athena_Generic_C::PlayerRunTemplate_Ground' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PlayerWalkTemplate_Ground) == 0x002908, "Member 'APlayerPawn_Athena_Generic_C::PlayerWalkTemplate_Ground' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PlayerRunTemplate_Water) == 0x002910, "Member 'APlayerPawn_Athena_Generic_C::PlayerRunTemplate_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PlayerWalkTemplate_Water) == 0x002918, "Member 'APlayerPawn_Athena_Generic_C::PlayerWalkTemplate_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Pawn_Charm_Skeletal_Mesh) == 0x002920, "Member 'APlayerPawn_Athena_Generic_C::Pawn_Charm_Skeletal_Mesh' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, AnimTrailsPS_Ref) == 0x002928, "Member 'APlayerPawn_Athena_Generic_C::AnimTrailsPS_Ref' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WeaponMaterialOverride) == 0x002930, "Member 'APlayerPawn_Athena_Generic_C::WeaponMaterialOverride' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, TickWaterLevel) == 0x002938, "Member 'APlayerPawn_Athena_Generic_C::TickWaterLevel' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WetnessDepthTexture) == 0x002940, "Member 'APlayerPawn_Athena_Generic_C::WetnessDepthTexture' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WaterLevelMID) == 0x002948, "Member 'APlayerPawn_Athena_Generic_C::WaterLevelMID' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, WaterDecayMID) == 0x002950, "Member 'APlayerPawn_Athena_Generic_C::WaterDecayMID' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Was_RTT_Enabled_Var_Set) == 0x002958, "Member 'APlayerPawn_Athena_Generic_C::Was_RTT_Enabled_Var_Set' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Is_RTT_Enabled) == 0x002959, "Member 'APlayerPawn_Athena_Generic_C::Is_RTT_Enabled' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, SlideAudioIntensity) == 0x00295C, "Member 'APlayerPawn_Athena_Generic_C::SlideAudioIntensity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, StartingMinCapsuleShadowVis) == 0x002960, "Member 'APlayerPawn_Athena_Generic_C::StartingMinCapsuleShadowVis' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, IsShielded) == 0x002964, "Member 'APlayerPawn_Athena_Generic_C::IsShielded' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, InstigatorCheckDistanceSqrd) == 0x002968, "Member 'APlayerPawn_Athena_Generic_C::InstigatorCheckDistanceSqrd' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, SlidingAudio_Inst) == 0x002970, "Member 'APlayerPawn_Athena_Generic_C::SlidingAudio_Inst' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, SlideDustActivateSpeed) == 0x002978, "Member 'APlayerPawn_Athena_Generic_C::SlideDustActivateSpeed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, CanSpawnSlideKickupFX_) == 0x00297C, "Member 'APlayerPawn_Athena_Generic_C::CanSpawnSlideKickupFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_Player_ShieldActivate) == 0x002980, "Member 'APlayerPawn_Athena_Generic_C::Effect_Player_ShieldActivate' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Effect_PLayer_ShieldBreak) == 0x002988, "Member 'APlayerPawn_Athena_Generic_C::Effect_PLayer_ShieldBreak' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, GhostMode) == 0x002990, "Member 'APlayerPawn_Athena_Generic_C::GhostMode' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, InAirAudioScalar) == 0x002994, "Member 'APlayerPawn_Athena_Generic_C::InAirAudioScalar' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, InAirAudio_Inst) == 0x002998, "Member 'APlayerPawn_Athena_Generic_C::InAirAudio_Inst' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, InAirAudioInterpSpeed) == 0x0029A0, "Member 'APlayerPawn_Athena_Generic_C::InAirAudioInterpSpeed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PawnSpeedAudioMin) == 0x0029A4, "Member 'APlayerPawn_Athena_Generic_C::PawnSpeedAudioMin' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, PawnSpeedAudioMax) == 0x0029A8, "Member 'APlayerPawn_Athena_Generic_C::PawnSpeedAudioMax' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_InAirLoop1P) == 0x0029B0, "Member 'APlayerPawn_Athena_Generic_C::Sound_InAirLoop1P' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Athena_Generic_C, Sound_InAirLoop3P) == 0x0029B8, "Member 'APlayerPawn_Athena_Generic_C::Sound_InAirLoop3P' has a wrong offset!");

}

