#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowdownLobbyPanel

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.ExecuteUbergraph_ShowdownLobbyPanel
// 0x0160 (0x0160 - 0x0000)
struct ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_5EA0949F4D6E4911006DC7AAD0BF22E2_Variable; // 0x0004(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UOverlaySlot*                           CallFunc_SlotAsOverlaySlot_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable1;                              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonUISubsystem*                     CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bUsingGamepad)>           K2Node_CreateDelegate_OutputDelegate;              // 0x0028(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_C521121942AEF996C7321E80CA7C7560_Variable; // 0x0038(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button2;                // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable1;                               // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortPartyContext*                      CallFunc_GetContext_ReturnValue;                   // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UShowdownTournamentScreen_C*            CallFunc_Create_ReturnValue;                       // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable2;                              // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetTournamentId_ReturnValue;              // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button1;                // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable2;                               // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue1;                  // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x00A0(0x0028)()
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue;                 // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue1;                // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue1;                  // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate1;             // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue1;              // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue;          // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue1;         // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue2;              // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue3;              // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue1;        // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_121[0x3];                                      // 0x0121(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue1;              // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue2;         // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue1;         // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable3;                              // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bUsingGamepad;                  // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x3];                                      // 0x0139(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select1_Default;                            // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select2_Default;                            // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_144[0x4];                                      // 0x0144(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue3;         // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0150(0x0010)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel) == 0x000008, "Wrong alignment on ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel");
static_assert(sizeof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel) == 0x000160, "Wrong size on ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, EntryPoint) == 0x000000, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::EntryPoint' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_bool_5EA0949F4D6E4911006DC7AAD0BF22E2_Variable) == 0x000004, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_bool_5EA0949F4D6E4911006DC7AAD0BF22E2_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_SlotAsOverlaySlot_ReturnValue) == 0x000008, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_SlotAsOverlaySlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_float_Variable) == 0x000010, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_float_Variable1) == 0x000014, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_float_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_bool_Variable) == 0x000018, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000020, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_CreateDelegate_OutputDelegate) == 0x000028, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_bool_C521121942AEF996C7321E80CA7C7560_Variable) == 0x000038, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_bool_C521121942AEF996C7321E80CA7C7560_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_ComponentBoundEvent_Button2) == 0x000040, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_ComponentBoundEvent_Button2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_bool_Variable1) == 0x000048, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetOwningPlayer_ReturnValue) == 0x000050, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetContext_ReturnValue) == 0x000058, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_Create_ReturnValue) == 0x000060, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_float_Variable2) == 0x000068, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_float_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetTournamentId_ReturnValue) == 0x000070, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetTournamentId_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_ComponentBoundEvent_Button1) == 0x000080, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_ComponentBoundEvent_Button1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_bool_Variable2) == 0x000088, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000090, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetContext_ReturnValue1) == 0x000098, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetContext_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_MakeStruct_SlateColor) == 0x0000A0, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_ComponentBoundEvent_Button) == 0x0000C8, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetStartTime_ReturnValue) == 0x0000D0, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetEndTime_ReturnValue) == 0x0000D4, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetStartTime_ReturnValue1) == 0x0000D8, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetStartTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_GetEndTime_ReturnValue1) == 0x0000DC, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_GetEndTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_CreateDelegate_OutputDelegate1) == 0x0000E0, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PauseAnimation_ReturnValue) == 0x0000F0, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0000F4, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000F8, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PauseAnimation_ReturnValue1) == 0x0000FC, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PauseAnimation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_Select_Default) == 0x000100, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_Add_FloatFloat_ReturnValue) == 0x000104, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PlayAnimationAtTime_ReturnValue) == 0x000108, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PlayAnimationAtTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PlayAnimationAtTime_ReturnValue1) == 0x000110, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PlayAnimationAtTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PauseAnimation_ReturnValue2) == 0x000118, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PauseAnimation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PauseAnimation_ReturnValue3) == 0x00011C, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PauseAnimation_ReturnValue3' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_LessEqual_FloatFloat_ReturnValue1) == 0x000120, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_LessEqual_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_Add_FloatFloat_ReturnValue1) == 0x000124, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_Add_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PlayAnimationAtTime_ReturnValue2) == 0x000128, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PlayAnimationAtTime_ReturnValue2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_Subtract_FloatFloat_ReturnValue1) == 0x000130, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_Subtract_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, Temp_float_Variable3) == 0x000134, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::Temp_float_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_CustomEvent_bUsingGamepad) == 0x000138, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_CustomEvent_bUsingGamepad' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_Select1_Default) == 0x00013C, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_Select2_Default) == 0x000140, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, CallFunc_PlayAnimationAtTime_ReturnValue3) == 0x000148, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::CallFunc_PlayAnimationAtTime_ReturnValue3' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel, K2Node_MakeStruct_Margin) == 0x000150, "Member 'ShowdownLobbyPanel_C_ExecuteUbergraph_ShowdownLobbyPanel::K2Node_MakeStruct_Margin' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.EventSwitchUI
// 0x0001 (0x0001 - 0x0000)
struct ShowdownLobbyPanel_C_EventSwitchUI final
{
public:
	bool                                          bUsingGamepad;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ShowdownLobbyPanel_C_EventSwitchUI) == 0x000001, "Wrong alignment on ShowdownLobbyPanel_C_EventSwitchUI");
static_assert(sizeof(ShowdownLobbyPanel_C_EventSwitchUI) == 0x000001, "Wrong size on ShowdownLobbyPanel_C_EventSwitchUI");
static_assert(offsetof(ShowdownLobbyPanel_C_EventSwitchUI, bUsingGamepad) == 0x000000, "Member 'ShowdownLobbyPanel_C_EventSwitchUI::bUsingGamepad' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'ShowdownLobbyPanel_C_BndEvt__EventDetailsButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.Refresh
// 0x0258 (0x0258 - 0x0000)
struct ShowdownLobbyPanel_C_Refresh final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable1;                               // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable2;                               // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable1;                              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable3;                               // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0018(0x0018)()
	class FText                                   Temp_text_Variable1;                               // 0x0030(0x0018)()
	bool                                          Temp_bool_A10E7D2E4AB7432758712A95D56AEA5F_Variable; // 0x0048(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0050(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue1;             // 0x0068(0x0018)()
	EFortShowdownEventState                       CallFunc_GetEventState_ReturnValue;                // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldShowCrossplayError_ReturnValue;     // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetCurrentEventScore_ReturnValue;         // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBestEventScore_ReturnValue;            // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetCurrentEventScore_ReturnValue1;        // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0090(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D8(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E8(0x0018)()
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0108(0x0018)()
	EFortShowdownEventState                       Temp_byte_Variable4;                               // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_SlotAsVerticalBoxSlot_ReturnValue;        // 0x0128(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select1_Default;                            // 0x0130(0x0018)()
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue;                 // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue1;              // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_155[0x3];                                      // 0x0155(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue;          // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable2;                              // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0170(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue1;           // 0x0188(0x0018)()
	class FText                                   CallFunc_TextToUpper_ReturnValue1;                 // 0x01A0(0x0018)()
	class FText                                   CallFunc_TextToUpper_ReturnValue2;                 // 0x01B8(0x0018)()
	int32                                         CallFunc_GetTournamentPinUnlockScore_ReturnValue;  // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x01D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D5[0x3];                                      // 0x01D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select2_Default;                            // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x01DC(0x0010)(IsPlainOldData, NoDestructor)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x01F0(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_209[0x7];                                      // 0x0209(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select3_Default;                            // 0x0210(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select4_Default;                            // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_219[0x3];                                      // 0x0219(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetTournamentPinUnlockScore_ReturnValue1; // 0x021C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0220(0x0018)()
	class FString                                 CallFunc_GetEventId_ReturnValue;                   // 0x0238(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable4;                               // 0x0249(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_24A[0x2];                                      // 0x024A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select5_Default;                            // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue1;         // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownLobbyPanel_C_Refresh) == 0x000008, "Wrong alignment on ShowdownLobbyPanel_C_Refresh");
static_assert(sizeof(ShowdownLobbyPanel_C_Refresh) == 0x000258, "Wrong size on ShowdownLobbyPanel_C_Refresh");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_byte_Variable) == 0x000000, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_Variable) == 0x000001, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_Variable1) == 0x000002, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_byte_Variable1) == 0x000003, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_byte_Variable2) == 0x000004, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_byte_Variable3) == 0x000005, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_Variable2) == 0x000006, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_float_Variable) == 0x000008, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_float_Variable1) == 0x00000C, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_float_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_Variable3) == 0x000010, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_text_Variable) == 0x000018, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_text_Variable1) == 0x000030, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_text_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_A10E7D2E4AB7432758712A95D56AEA5F_Variable) == 0x000048, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_A10E7D2E4AB7432758712A95D56AEA5F_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_MakeLiteralText_ReturnValue) == 0x000050, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_MakeLiteralText_ReturnValue1) == 0x000068, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_MakeLiteralText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetEventState_ReturnValue) == 0x000080, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetEventState_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_ShouldShowCrossplayError_ReturnValue) == 0x000081, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_ShouldShowCrossplayError_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetCurrentEventScore_ReturnValue) == 0x000084, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetCurrentEventScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetBestEventScore_ReturnValue) == 0x000088, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetBestEventScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetCurrentEventScore_ReturnValue1) == 0x00008C, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetCurrentEventScore_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_MakeStruct_FormatArgumentData) == 0x000090, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Greater_IntInt_ReturnValue) == 0x0000D0, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_MakeArray_Array) == 0x0000D8, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Format_ReturnValue) == 0x0000E8, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select_Default) == 0x000100, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_TextToUpper_ReturnValue) == 0x000108, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_byte_Variable4) == 0x000120, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_byte_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_SlotAsVerticalBoxSlot_ReturnValue) == 0x000128, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_SlotAsVerticalBoxSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select1_Default) == 0x000130, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_PauseAnimation_ReturnValue) == 0x000148, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetStartTime_ReturnValue) == 0x00014C, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_PauseAnimation_ReturnValue1) == 0x000150, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_PauseAnimation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000154, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Add_FloatFloat_ReturnValue) == 0x000158, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetEndTime_ReturnValue) == 0x00015C, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_PlayAnimationAtTime_ReturnValue) == 0x000160, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_PlayAnimationAtTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000168, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_float_Variable2) == 0x00016C, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_float_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Conv_StringToText_ReturnValue) == 0x000170, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Conv_StringToText_ReturnValue1) == 0x000188, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Conv_StringToText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_TextToUpper_ReturnValue1) == 0x0001A0, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_TextToUpper_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_TextToUpper_ReturnValue2) == 0x0001B8, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_TextToUpper_ReturnValue2' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetTournamentPinUnlockScore_ReturnValue) == 0x0001D0, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetTournamentPinUnlockScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x0001D4, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select2_Default) == 0x0001D8, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_MakeStruct_Margin) == 0x0001DC, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetText_ReturnValue) == 0x0001F0, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_TextIsEmpty_ReturnValue) == 0x000208, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select3_Default) == 0x000210, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select3_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select4_Default) == 0x000218, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select4_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetTournamentPinUnlockScore_ReturnValue1) == 0x00021C, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetTournamentPinUnlockScore_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_Conv_IntToText_ReturnValue) == 0x000220, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_GetEventId_ReturnValue) == 0x000238, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_GetEventId_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000248, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, Temp_bool_Variable4) == 0x000249, "Member 'ShowdownLobbyPanel_C_Refresh::Temp_bool_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, K2Node_Select5_Default) == 0x00024C, "Member 'ShowdownLobbyPanel_C_Refresh::K2Node_Select5_Default' has a wrong offset!");
static_assert(offsetof(ShowdownLobbyPanel_C_Refresh, CallFunc_PlayAnimationAtTime_ReturnValue1) == 0x000250, "Member 'ShowdownLobbyPanel_C_Refresh::CallFunc_PlayAnimationAtTime_ReturnValue1' has a wrong offset!");

// Function ShowdownLobbyPanel.ShowdownLobbyPanel_C.InputTypeChanged
// 0x0001 (0x0001 - 0x0000)
struct ShowdownLobbyPanel_C_InputTypeChanged final
{
public:
	bool                                          isGamepad;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ShowdownLobbyPanel_C_InputTypeChanged) == 0x000001, "Wrong alignment on ShowdownLobbyPanel_C_InputTypeChanged");
static_assert(sizeof(ShowdownLobbyPanel_C_InputTypeChanged) == 0x000001, "Wrong size on ShowdownLobbyPanel_C_InputTypeChanged");
static_assert(offsetof(ShowdownLobbyPanel_C_InputTypeChanged, isGamepad) == 0x000000, "Member 'ShowdownLobbyPanel_C_InputTypeChanged::isGamepad' has a wrong offset!");

}

