#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TournamentEventWindowDetails

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function TournamentEventWindowDetails.TournamentEventWindowDetails_C.ExecuteUbergraph_TournamentEventWindowDetails
// 0x02F0 (0x02F0 - 0x0000)
struct TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	class FText                                   Temp_text_Variable1;                               // 0x0020(0x0018)()
	class FText                                   Temp_text_Variable2;                               // 0x0038(0x0018)()
	class FText                                   Temp_text_Variable3;                               // 0x0050(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownMatchType                        Temp_byte_Variable2;                               // 0x006B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable1;                                // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable2;                                // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable3;                                // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable4;                                // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable5;                                // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_64EBE1CD4989DF0E505BA38D18DC4503_Variable; // 0x0084(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0088(0x0018)()
	EFortShowdownEventState                       CallFunc_GetEventState_ReturnValue;                // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownMatchType                        CallFunc_GetTournamentMatchType_ReturnValue;       // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A2[0x6];                                       // 0x00A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue;          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select_Default;                             // 0x00B0(0x0018)()
	int32                                         Temp_int_Variable6;                                // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x00D0(0x0018)()
	class FText                                   CallFunc_GetText_ReturnValue1;                     // 0x00E8(0x0018)()
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue1;         // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable7;                                // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0110(0x0018)()
	int32                                         Temp_int_Variable8;                                // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue1;                 // 0x0130(0x0018)()
	EFortShowdownEventState                       Temp_byte_Variable3;                               // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownMatchType                        CallFunc_GetTournamentMatchType_ReturnValue1;      // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14A[0x2];                                      // 0x014A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select1_Default;                            // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x3];                                      // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetTournamentPinUnlockScore_ReturnValue;  // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue;                 // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue1;              // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0164(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_165[0x3];                                      // 0x0165(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue2;         // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDateTime                              CallFunc_GetEventBeginTime_ReturnValue;            // 0x0180(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetEventTimeAsText_ReturnValue;           // 0x0188(0x0018)()
	struct FDateTime                              CallFunc_GetEventEndTime_ReturnValue;              // 0x01A0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01A8(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetEventTimeAsText_ReturnValue1;          // 0x01E8(0x0018)()
	bool                                          Temp_bool_Variable1;                               // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData1;             // 0x0208(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0248(0x0010)(ZeroConstructor, ReferenceParm)
	float                                         K2Node_Select2_Default;                            // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0260(0x0018)()
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationAtTime_ReturnValue3;         // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_TextText_ReturnValue;            // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              CallFunc_GetEventBeginTime_ReturnValue1;           // 0x0288(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFortShowdownEventBestResultsSummary   CallFunc_GetEventResultsSummary_ReturnValue;       // 0x0290(0x0014)(NoDestructor)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetEventDateAsText_ReturnValue;           // 0x02A8(0x0018)()
	bool                                          CallFunc_NotEqual_TextText_ReturnValue1;           // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x02C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select3_Default;                            // 0x02C3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C4[0x4];                                      // 0x02C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x02C8(0x0028)()
};
static_assert(alignof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails) == 0x000008, "Wrong alignment on TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails");
static_assert(sizeof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails) == 0x0002F0, "Wrong size on TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, EntryPoint) == 0x000000, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::EntryPoint' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_text_Variable) == 0x000008, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_text_Variable1) == 0x000020, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_text_Variable1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_text_Variable2) == 0x000038, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_text_Variable2' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_text_Variable3) == 0x000050, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_text_Variable3' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_bool_Variable) == 0x000068, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_byte_Variable) == 0x000069, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_byte_Variable1) == 0x00006A, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_byte_Variable2) == 0x00006B, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable) == 0x00006C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable1) == 0x000070, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable2) == 0x000074, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable3) == 0x000078, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable3' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable4) == 0x00007C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable4' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable5) == 0x000080, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable5' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_bool_64EBE1CD4989DF0E505BA38D18DC4503_Variable) == 0x000084, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_bool_64EBE1CD4989DF0E505BA38D18DC4503_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetText_ReturnValue) == 0x000088, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventState_ReturnValue) == 0x0000A0, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventState_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetTournamentMatchType_ReturnValue) == 0x0000A1, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetTournamentMatchType_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PlayAnimationAtTime_ReturnValue) == 0x0000A8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PlayAnimationAtTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_Select_Default) == 0x0000B0, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable6) == 0x0000C8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable6' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_TextToUpper_ReturnValue) == 0x0000D0, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetText_ReturnValue1) == 0x0000E8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PlayAnimationAtTime_ReturnValue1) == 0x000100, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PlayAnimationAtTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable7) == 0x000108, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable7' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_Conv_StringToText_ReturnValue) == 0x000110, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_int_Variable8) == 0x000128, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_int_Variable8' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_TextToUpper_ReturnValue1) == 0x000130, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_TextToUpper_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_byte_Variable3) == 0x000148, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetTournamentMatchType_ReturnValue1) == 0x000149, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetTournamentMatchType_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_Select1_Default) == 0x00014C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000150, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetTournamentPinUnlockScore_ReturnValue) == 0x000154, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetTournamentPinUnlockScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PauseAnimation_ReturnValue) == 0x000158, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetStartTime_ReturnValue) == 0x00015C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PauseAnimation_ReturnValue1) == 0x000160, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PauseAnimation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000164, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_Add_FloatFloat_ReturnValue) == 0x000168, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEndTime_ReturnValue) == 0x00016C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PlayAnimationAtTime_ReturnValue2) == 0x000170, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PlayAnimationAtTime_ReturnValue2' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000178, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_float_Variable) == 0x00017C, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventBeginTime_ReturnValue) == 0x000180, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventBeginTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventTimeAsText_ReturnValue) == 0x000188, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventTimeAsText_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventEndTime_ReturnValue) == 0x0001A0, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_MakeStruct_FormatArgumentData) == 0x0001A8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventTimeAsText_ReturnValue1) == 0x0001E8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventTimeAsText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, Temp_bool_Variable1) == 0x000200, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_MakeStruct_FormatArgumentData1) == 0x000208, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_MakeStruct_FormatArgumentData1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_MakeArray_Array) == 0x000248, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_Select2_Default) == 0x000258, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_Format_ReturnValue) == 0x000260, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_PlayAnimationAtTime_ReturnValue3) == 0x000278, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_PlayAnimationAtTime_ReturnValue3' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_NotEqual_TextText_ReturnValue) == 0x000280, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_NotEqual_TextText_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventBeginTime_ReturnValue1) == 0x000288, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventBeginTime_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventResultsSummary_ReturnValue) == 0x000290, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventResultsSummary_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_GetEventDateAsText_ReturnValue) == 0x0002A8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_GetEventDateAsText_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_NotEqual_TextText_ReturnValue1) == 0x0002C0, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_NotEqual_TextText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_Greater_IntInt_ReturnValue) == 0x0002C1, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, CallFunc_BooleanAND_ReturnValue) == 0x0002C2, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_Select3_Default) == 0x0002C3, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_Select3_Default' has a wrong offset!");
static_assert(offsetof(TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails, K2Node_MakeStruct_SlateColor) == 0x0002C8, "Member 'TournamentEventWindowDetails_C_ExecuteUbergraph_TournamentEventWindowDetails::K2Node_MakeStruct_SlateColor' has a wrong offset!");

}

